<a href="https://colab.research.google.com/github/GhazalehKeyvani/Avina/blob/main/MLCrashCourse/fa_Numpy_Pandas_dataframe_UltraQuick_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy
[Numpy](https://numpy.org/doc/stable/index.html) یک کتابخانه ی پایتون است که
ماتریکس که ساختمان داده ی اصلی مورد استفاده برای الگوریتم های یادگیری ماشین است که داده ها را به صورت ردیفی و ستونی ذخیره سازی می کند.

معادل ماتریکس ریاضیاتی در موارد زیر
* python : lists
* numpy : arrays
* TensorFlow : tensors

##Import NumPy module

In [ ]:
import numpy as np


ایجاد آرایه با اعداد مشخص
*   np.array



##آرایه ی یک بعدی

In [ ]:
one_dimentional_array = np.array([2.3, 4.03, 4.5, 3.9])
print(one_dimentional_array)

[2.3  4.03 4.5  3.9 ]


##آرایه ی 2 بعدی

In [ ]:
two_dimentional_array = np.array([[2.3,0], [4.03,3], [4.5,6], [3.9,4]])
print(two_dimentional_array)

[[2.3  0.  ]
 [4.03 3.  ]
 [4.5  6.  ]
 [3.9  4.  ]]


##ساخت آرایه ی از 0
* np.zeros

##ساخت آرایه ی از 1
* np.ones

In [ ]:
np.ones(4)
np.zeros(4)

array([0., 0., 0., 0.])

##ساخت آرایه ی از دنباله ای از اعداد

In [ ]:
sequence_of_intigers=np.arange(5,25)
print(sequence_of_intigers)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


دقت کنید که از کوچکترین تا یکس مانده به آخرین عدد در این تابع آورده میشود و 25 در آن نیست

##ساخت آرایه ی از اعداد تصادفی

In [ ]:
random_integers_between_30_and_75 = np.random.randint(low=30,high=76,size=8)
print(random_integers_between_30_and_75)

[64 73 75 74 65 67 50 37]


In [ ]:
random_floats_between_0_and_1 = np.random.random([8])
print(random_floats_between_0_and_1)

[0.2978579  0.67577598 0.87503708 0.68845291 0.35687776 0.52982238
 0.54850804 0.50050928]


## عملیات های ریاضی در numpy

اگر می خواهید دو آرایه را اضافه یا کم کنید، جبر خطی مستلزم آن است که دو عملوند دارای ابعاد یکسانی باشند. علاوه بر این، اگر می خواهید دو آرایه را ضرب کنید، جبر خطی قوانین سختگیرانه ای را بر سازگاری ابعادی عملوندها اعمال می کند. خوشبختانه، NumPy از ترفندی به نام پخش استفاده می‌کند تا عملوند کوچک‌تر را به ابعادی که برای جبر خطی سازگار است، بسط دهد. به عنوان مثال، عملیات زیر از پخش برای اضافه کردن 2.0 به مقدار هر آیتم در آرایه ایجاد شده در سلول کد قبلی استفاده می کند:

In [ ]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.2978579  2.67577598 2.87503708 2.68845291 2.35687776 2.52982238
 2.54850804 2.50050928]


پخش در ضرب

In [ ]:
random_integers_between_60_and_150 = random_integers_between_30_and_75 *2
print(random_integers_between_60_and_150)

[128 146 150 148 130 134 100  74]


تمرین 1:یک دیتاست خطی ایجاد کنید


> هدف ایجاد یک دیتاست ساده با یک فیچر و برچسب آن است



1.    دنباله ای از اعداد صحیح از 6 تا 20 به صورت numpy array
2.   برچسب گزاری 15  تا از آنها







In [ ]:
feature = np.arange(6,21)
print(feature)
label = (feature*3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


تمرین 2:
تعدادی noise به دیتاست اضافه کنید .


> دیتاست را کمی واقعی تر کنیدو به آن
noise
های تصادفی بیفزایید با افزودن یک سری
اعداد تصادفی بین -2 , 2








In [ ]:
noise = (np.random.random([15]) * 4)-2
print(noise)
label = noise + label
print(label)

[-0.08743327  1.23214637 -0.94929191  1.62941158 -1.70572411 -1.48742196
 -1.44894025  0.27778523  1.66376771  1.79391725  0.28213797  0.76417225
  0.53593718 -0.9062201   0.83314504]
[20.15396475 24.95744876 27.47629653 30.70380744 34.02867619 35.18196544
 39.56035744 42.75654723 46.71056034 50.92275635 53.06902421 56.25431318
 60.47554443 60.05801252 64.8309942 ]


# Pandas DataFrame
دیتا فرم ساختار مرکزی داده در pandas API
است
یک دیتا فریم شبیه یک spreadsheet است که در memory ذخیره شده


*   یک دیتافریم داده ها را در سلول ها ذخیره می کند
*   یک دیتافریم ستون هایش نام گزاری می شوند و ردیف هایش شماره گذاری میشود



In [ ]:
import numpy as np
import pandas as pd

#Creating DataFrame



*   5 ردیف
*   2 ستون با نام tempreture , activity
pd.Dataframe برای ساخت یک دیتا فریم 2 آرگومان می گیرد
* اولین آرگومان داده را در 10 سلول ارائه میدهد np.array 5X2 numpy array
* دومین آرگومان نام ستون ها را مشخص می کند



In [ ]:
my_data = np.array([[0,3],[10,7],[20,9],[30,14],[40,15]])

my_column_names = ['temperature','activity']

my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


In [ ]:
print("Rows #0, #1, and #2:")
print(my_dataframe.head(3), '\n')

print("Row #2:")
print(my_dataframe.iloc[[2]], '\n')

print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

print("Column 'temperature':")
print(my_dataframe['temperature'])

Rows #0, #1, and #2:
   temperature  activity
0            0         3
1           10         7
2           20         9 

Row #2:
   temperature  activity
2           20         9 

Rows #1, #2, and #3:
   temperature  activity
1           10         7
2           20         9
3           30        14 

Column 'temperature':
0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int64


تمرین1: یک دیتافریم ایجاد کنید


1.   3X4 Eleanor, Chidi, Tahani, Jason 12 سلول که در آنها 0تا 100 به صورت تصادفی

1.   خروجی موارد زیر است


*   کل دیتا فریم
*   ردیف اول Eleanor درسلول ها را خروجی دهید


2.   ایجاد نام ستون پنجم Janet ردیف

مجموع tahani , jason



In [ ]:
#@title Double-click for a solution to Task 1.

# Create a Python list that holds the names of the four columns.
my_column_names = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

# Create a 3x4 numpy array, each cell populated with a random integer.
my_data = np.random.randint(low=0, high=101, size=(3, 4))

# Create a DataFrame.
df = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(df)

# Print the value in row #1 of the Eleanor column.
print("\nSecond row of the Eleanor column: %d\n" % df['Eleanor'][1])

# Create a column named Janet whose contents are the sum
# of two other columns.
df['Janet'] = df['Tahani'] + df['Jason']

# Print the enhanced DataFrame
print(df)

   Eleanor  Chidi  Tahani  Jason
0       77     42      13     48
1       82     59      51     45
2       93     70      72      7

Second row of the Eleanor column: 82

   Eleanor  Chidi  Tahani  Jason  Janet
0       77     42      13     48     61
1       82     59      51     45     96
2       93     70      72      7     79


In [ ]:
#@title Double-click for a solution to Task 1.

# Create a Python list that holds the names of the four columns.
my_column_names = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

# Create a 3x4 numpy array, each cell populated with a random integer.
my_data = np.random.randint(low=0, high=101, size=(3, 4))

# Create a DataFrame.
df = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(df)

# Print the value in row #1 of the Eleanor column.
print("\nSecond row of the Eleanor column: %d\n" % df['Eleanor'][1])

# Create a column named Janet whose contents are the sum
# of two other columns.
df['Janet'] = df['Tahani'] + df['Jason']

# Print the enhanced DataFrame
print(df)

   Eleanor  Chidi  Tahani  Jason
0       42     75      75     72
1       87     99      94     38
2       24     10       7     67

Second row of the Eleanor column: 87

   Eleanor  Chidi  Tahani  Jason  Janet
0       42     75      75     72    147
1       87     99      94     38    132
2       24     10       7     67     74


##کپی یک دیتافریم


*   Refrencing
اگر یک دیتافریم را به یک متغییر جدید  ذخیره کنیم وتغییراتی در آن ایجاد کنیم تاثیر آن را در دیتافریم اولیه نیز می بینیم  
*   Copying
اما اگر np.DataFrame.copy را استفاده کنیم با تغییر در دیتافریم انعکاس آن را در دیگری نخواهیم دید


In [ ]:
# Create a reference by assigning my_dataframe to a new variable.
print("Experiment with a reference:")
reference_to_df = df

# Print the starting value of a particular cell.
print("  Starting value of df: %d" % df['Jason'][1])
print("  Starting value of reference_to_df: %d\n" % reference_to_df['Jason'][1])

# Modify a cell in df.
df.at[1, 'Jason'] = df['Jason'][1] + 5
print("  Updated df: %d" % df['Jason'][1])
print("  Updated reference_to_df: %d\n\n" % reference_to_df['Jason'][1])

# Create a true copy of my_dataframe
print("Experiment with a true copy:")
copy_of_my_dataframe = my_dataframe.copy()

# Print the starting value of a particular cell.
print("  Starting value of my_dataframe: %d" % my_dataframe['activity'][1])
print("  Starting value of copy_of_my_dataframe: %d\n" % copy_of_my_dataframe['activity'][1])

# Modify a cell in df.
my_dataframe.at[1, 'activity'] = my_dataframe['activity'][1] + 3
print("  Updated my_dataframe: %d" % my_dataframe['activity'][1])
print("  copy_of_my_dataframe does not get updated: %d" % copy_of_my_dataframe['activity'][1])

Experiment with a reference:
  Starting value of df: 38
  Starting value of reference_to_df: 38

  Updated df: 43
  Updated reference_to_df: 43


Experiment with a true copy:


KeyError: ignored